// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_appsync_graphqlEndpoint": "ADD YOUR CREDENTIALS",
    "aws_appsync_region": "ADD YOUR CREDENTIALS",
    "aws_appsync_authenticationType": "ADD YOUR CREDENTIALS",
    "aws_appsync_apiKey": "ADD YOUR CREDENTIALS",
};

export default awsmobile;